The_Iron_Bank/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from bank_records_app.views import UserCreateView, IndexView, TransactionView, TransactionListCreateAPIView, \
                                   TransactionCreateView, TransactionDetailAPIView

from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')),
    url(r'^obtain-token/$', obtain_auth_token),
    url(r'^$', IndexView.as_view(), name="index_view"),
    url(r'^create_user/$', UserCreateView.as_view(), name="user_create_view"),
    url(r'^user_transactions/$', TransactionView.as_view(), name="transactions"),
    url(r'^create_transaction/$', TransactionCreateView.as_view(), name="user_transaction_create_view"),
    # API URLs
    url(r'^transactions_api/$', TransactionListCreateAPIView.as_view(), name="transaction_list_create_api_view"),
    url(r'^transaction/(?P<pk>\d+)/$', TransactionDetailAPIView.as_view(), name="transaction_detail_api_view")
]

bank_records_app/models.py
from django.db import models

from django.dispatch import receiver
from django.db.models.signals import post_save


from django.conf import settings
from rest_framework.authtoken.models import Token


# Create your models here.


class Account(models.Model):

    user = models.OneToOneField('auth.User')
    created = models.DateTimeField(auto_now_add=True)

    @property
    def get_balance(self):
        account_transactions = Transaction.objects.filter(user=self.user)
        total = 0
        for transaction in account_transactions:
            if transaction.debit_or_deposit == '+':
                total += transaction.amount
            elif transaction.debit_or_deposit == '-':
                total -= transaction.amount
        return total

    def __str__(self):
        return str(self.user)


@receiver(post_save, sender='auth.User')
def create_user_profile(**kwargs):
    created = kwargs.get('created')
    instance = kwargs.get('instance')
    if created:
        Account.objects.create(user=instance)


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)


DEBIT_OR_DEPOSIT = [
    ('+', 'Deposit'),
    ('-', 'Withdraw'),
]


class Transaction(models.Model):
    user = models.ForeignKey('auth.User')
    debit_or_deposit = models.CharField(max_length=1, choices=DEBIT_OR_DEPOSIT)
    amount = models.FloatField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user)

bank_records_app/views.py
# from django.shortcuts import render

from rest_framework.generics import ListCreateAPIView, RetrieveAPIView

from bank_records_app.serializers import TransactionSerializer

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import ListView, TemplateView
from django.views.generic.edit import CreateView


from bank_records_app.models import Transaction

from rest_framework.permissions import IsAuthenticated

# Create your views here.


class UserCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = "/"


class IndexView(TemplateView):
        template_name = 'index.html'


class TransactionCreateView(CreateView):
    model = Transaction
    success_url = "/user_transactions"
    fields = ('amount', 'debit_or_deposit')

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user = self.request.user
        return super().form_valid(form)


class TransactionView(ListView):
    template_name = 'transactions.html'
    model = Transaction

    def get_queryset(self):
        return Transaction.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['transactions'] = Transaction.objects.filter(user=self.request.user)
        return context


# API Views

# class TransactionListCreateAPIView(ListCreateAPIView):
#     queryset = Transaction.objects.all()
#     serializer_class = TransactionSerializer
#
#     def perform_create(self, serializer):
#         # print(serializer)
#         # print(serializer.data)
#         serializer.save(created_by=self.request.user)
#         return super().perform_create(serializer)


class TransactionListCreateAPIView(ListCreateAPIView):
    permission_classes = (IsAuthenticated, )
    # queryset = Transaction.objects.all()

    serializer_class = TransactionSerializer

    def get_queryset(self):
        return Transaction.objects.filter(user=self.request.user)

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)
        return super().perform_create(serializer)


class TransactionDetailAPIView(RetrieveAPIView):
    # queryset = Transaction.objects.all()
    serializer_class = TransactionSerializer
    permission_classes = (IsAuthenticated, )

    def get_queryset(self):
        return Transaction.objects.filter(user=self.request.user)

templates/account.html
{% extends 'base.html' %}
{% block content %}

      {% if request.user.profile.is_owner %}
{% for operation in object_list %}

  <div class="panel panel-default">
    <div class="panel-heading">

  <h3 class="panel-title">{% if operation.description %}
    Reason for operation:<br>{{ operation.description }}</h3>{% endif %}
</div>
  <div class="panel-body">
    <p>{{ operation.num1 }} {{ operation.operator }}  {{ operation.num2 }} = {{ operation.do_the_math }}</p>
    <p style="color: orange"><br>
      By: {{ operation.created_by }}
    </p>

  </div>
    </div>
          {% endfor %}
        {% endif %}



{% for operation in object_list %}
    {% if request.user == operation.created_by %}

    <div class="panel panel-default">
      <div class="panel-heading">

    <h3 class="panel-title">{% if operation.description %}
      Reason for operation:<br>{{ operation.description }}</h3>{% endif %}
  </div>
    <div class="panel-body">
      <p>{{ operation.num1 }} {{ operation.operator }}  {{ operation.num2 }} = {{ operation.do_the_math }}</p>
      <p style="color: orange"><br>
        By: {{ operation.created_by }}
      </p>

    </div>
      </div>

{% endif %}

{% endfor %}

{% endblock %}

templates/accounts.html
{% extends 'base.html' %}
{% block content %}



{% for action in transaction %}

    <div class="panel panel-default">
      <div class="panel-heading">

    <h3 class="panel-title">{% if transaction.description %}
      Reason for transaction:<br>{{ transaction.description }}</h3>{% endif %}
  </div>
    <div class="panel-body">
      <p>{{ transaction.debit_or_deposit }}{{ transaction.amount }} = {{ transaction.get_balance }}</p>
    </div>
      </div>

      <p>
        {{ account.get_balance }}
      </p>

    {% endfor %}

{% endblock %}

templates/bank_records_app/transaction_form.html
{% extends 'base.html' %}

{% block content %}
<div class="well">
  <h1>Transaction </h1>


  <form class="" action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
  <input type="submit" name="" value="Confirm">

  </form>

</div>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}MoneyStash{% endblock %}</title>
    <!-- <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" media="screen" title="no title"> -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

    <style media="screen">
      body {
        background-color: black; font-family:sans-serif;
        background-image:url('/static/images/GOLD.jpg');


        background-size:cover;
        }
      .navbar-default {
        background-color: #1D4C6B;
        background-image:
        border-color: #1D4C6B;
        }
        .btn
        {
          background-color: #f5dd5d;
          border-color: white;
        }
  </style>
  </head>

  <body>
    <!-- <img src="static/images/GOLD.jpg" /> -->

    <div class="container">


    <nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <ul class="nav navbar-nav">

    <li><a href="{% url 'index_view' %}"><button type="button" class="btn btn-default navbar-btn">Home</button></a></li>

        {% if not request.user.is_authenticated %}
    <li><a href="{% url 'login' %}"><button type="button" class="btn btn-default navbar-btn">Log In</button></a></li>
    <li><a href="{% url 'user_create_view' %}"><button type="button" class="btn btn-default navbar-btn">Create Account</button></a></li>
        {% else %}
    <li><a href="{% url 'login' %}"><button type="button" class="btn btn-default navbar-btn">Change Account</button></a></li>
        {% endif %}

    {% if request.user.is_authenticated %}
    <li><a href="{% url 'transactions' %}"><button type="button" class="btn btn-default navbar-btn">Account History</button></a></li>
    <li><a href="{% url 'logout' %}?next={% url 'index_view' %}"><button style="background-color: #72B73A;" type="button" class="btn btn-default navbar-btn">Log out</button></a></li>
    <li><a href="{% url 'user_transaction_create_view' %}"><button style="background-color: #ba2121"type="button" class="btn btn-default navbar-btn">New Transaction</button></a></li>
    <li><a href="{% url 'transaction_list_create_api_view' %}"><button type="button" class="btn btn-default navbar-btn">DRF</button></a></li>


    {% endif %}

    <!-- <h1>💰💰💰💰💰💰💰💰💰💰💰💰💰💰💰💰💰💰💰💰💰💰💰💰💰💰💰💰💰💰💰💰💰💰💰💰💰💰💰💰</h1> -->

  </ul>
  </div>
</nav>


{% if not request.user.is_authenticated %}
<p>
  <h3 style="color:white">Welcome! You are not logged in. <a style="color: lightgrey;" href="{% url 'login' %}">Log in</a>? Or <a style="color: lightgrey;" href="{% url 'user_create_view' %}">create an account?</a></h3>
</p>
{% else %}
      <p> <h3 style="color:white">Welcome, {{ request.user }}</h3></p>
{% endif %}
<hr><br>



    {% block content %}
    {% endblock %}

    </div>

  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="well">
<h3>The word bank was borrowed in Middle English from Middle French banque, from Old Italian banca, meaning "table", from Old High German banc, bank "bench, counter". Benches were used as makeshift desks or exchange counters during the Renaissance by Jewish Florentine bankers, who used to make their transactions atop desks covered by green tablecloths.</h3>
</div>

{% endblock %}

templates/transactions.html
{% extends 'base.html' %}
{% block content %}

<div class="well">

<h2>
  Balance: {{ request.user.account.get_balance }}0
</h2>

</div>
<div class="panel panel-default">
  <div class="panel-heading">

    {% if not object_list %}
    <p>No records found.</p>
    {% endif %}

    {% for transaction in object_list %}

      <h3 class="panel-title">
      </div>
      <div class="panel-body">
        <h4>{% if transaction.debit_or_deposit == '-' %}
    <span style = "color: red;">{{ transaction.get_debit_or_deposit_display }}</span>:
        {% elif transaction.debit_or_deposit == '+' %}
    <span style = "color: green;">{{ transaction.get_debit_or_deposit_display }}</span>:
        {% endif %}
        {{ transaction.amount }}  <h6>{{ transaction.created }}</h6></h4>
        <h4>{% if transaction.debit_or_deposit == '-' %}
      <hr style="border-color: red;">
        {% elif transaction.debit_or_deposit == '+' %}
      <hr style="border-color: green;">
        {% endif %}
     </h3>

{% endfor %}

  </div>
</div>

{% endblock %}